### ISSUE TITLE
Further improvement of #287

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#1004]
#287 has been developed but the implemented solution could still be improved.
- [x] add a test to check if a source is global at the time of deletion (source & project)
- [x] display the list of views shared with other projects when deleting a project

![image](https://github.com/unep-grid/mapx/assets/19908801/340d7d1f-f3b6-4c37-809d-10fcb79f4f65)

**Comment by antobenve** [comment]
For the second point, I would prefer having the name of the project (or ID) instead of "Yes" under the column "Shared" as it was suggested in the issue #994 .
