### ISSUE TITLE
Story maps: message when leaving the content edit mode without saving is not available in English (and Bengali)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#1018]
The translation of the following message is not available in English (and in Bengali). 

`Vos changements n'ont pas été enregistrés, êtes-vous sûr de vouloir les perdre?
`

The message is displayed when leaving the edit mode of the slide of a story map without saving the latest edits.

**Comment by fxi** [comment]
- Bengali is not supported, in this part of the app.
- The manoeuvre
` english -> edit  story -> quit -> change language -> re-open edit story -> quit  -> change language back to english [warning message ] ` is now working

**Comment by thomaspiller** [comment]
I just tried the manipulation explained in the previous comment and the message is always in English. In addition, I have the impression that the panel is not constantly displayed (I may have misunderstood what manipulations trigger its display) @antobenve Could you take a look at it ASAP?

**Comment by fxi** [comment]
1) A language change from <non english> to <english> was not properly handled. Changed in 65a2ceb, as mentioned in the change log
2) The editor should be in the current app language, not "always english". If so, there is another bug
3) If there was no edit, the panel should not be displayed.

**Comment by thomaspiller** [comment]
My bad. That's all good, the edit panel and message are in the language selected in the MapX UI. Language changes are handled well.

**Comment by antobenve** [comment]
All good in my opinion too.
