### ISSUE TITLE
Changing project while the story map edition panel is open causes error

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#1024]
If the project is changed without closing the module for the edition of a story map, the new project loads but the content of the views' panel doesn't. An error is sent to console:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'types')
`

**Comment by thomaspiller** [comment]
I just tested the patch and the list of views still does not load. The error is however different: `TypeError: r is undefined`.

**Comment by fxi** [comment]
Race condition ? 

https://github.com/user-attachments/assets/3a924bc2-bb4c-44b6-abc0-82e1ce50e7cf

**Comment by fxi** [comment]
ok. If you are doing that very slowly, there is an issue. I'll check that.
