### ISSUE TITLE
Feature Request: Support OGC Compliant Sharing Protcolls for data in MapX

### ISSUE THREAD

**Issue by Jo-Schie** [unep-grid/mapx#1032]
Hello there,

I wondered if it was possible to support OGC compliant sharing protocolls in MapX (WMS/WMTS/WFS,TMS and/or similar). In my dreamworld every layer in your platform would have e.g. a WMS link that I could integrate into QGIS or other GIS software. 

Background: These protocolls allow other geospatial platforms or GIS to integrate data from MapX in their own applications and vice versa. In my institution we use the GeoNode software which is OGC compliant. We are able to easily stream data from e.g. FAO which is also OGC compliant. This is very usefull and helps our project managers to access high quality data for drought monitoring, which in return can help to better allocate bilateral development aid for combating drought and dangerous climate change. 

Currently MapX data is in a data silo (or did I miss a detail?) and so the data from GRID Geneva is not used as much as it could be used if it was easy to integrate into other platforms. Thats a pity for DPGs. IT basically means the uptake is very much reduced...becaue our users would have to use 2 plattforms or if we extrapolate that logic .... several platforms for different thematic purposes. This is not user-friendly and in reality impossible (amongst some of the factors being e.g. information security)...

**Comment by Jo-Schie** [comment]
Oh wow! You guys are great! I will test this out and, logically close this issue since the feature is already present! Great work!!!

**Comment by antobenve** [comment]
Thanks. It's a pleasure.

Happy use of MapX.

**Comment by antobenve** [comment]
Just to complete with some useful information:

**Some Caveats:**

- We use `geostyler` to convert styles, which may result in minor discrepancies. If you notice any issues, please report them.  
- Enabling OGC services is optional and depends on the source publisher's action. If the service should be activated, please contact the last editor of the view. As already said, licensing restrictions may prevent data from being re-shared, though this could also be an oversight.

And please contact us on info@mapx.org if you wish to continue the discussion on a less technical ground.
