### ISSUE TITLE
Select one or more date-attributes in conf.window for time-slider

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#137]
Allow publishers to set which attributes they want to set available to users to be used in the time slider. Attributes must be in "date"-format

1) The publisher could select one or more attributes from the list like the secondary variables are selected.
2) Users will perform a time slider on the available attribute. If more than one were set available by the publisher, users will select which one they want to use under "settings" where the time slider is.

**Comment by thomaspiller** [comment]
@antobenve Is it still relevant? This seems a bit complicated to set up in terms of user experience and we haven't discussed this in years.
