### ISSUE TITLE
Slider options (3) that are useful (continuous time, discrete for changing geometries, discrete for changing values but same geometries)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#213]
- [x] Time slider:
Slider through time values of a predefined attribute (respect the absolute distance in time).

- [ ] Discrete slider for different geometries:
Slider through absolute values of one specific attribute (to be set in the view's conf. window). Features with the same value are shown together.

- [ ] Discrete slider for same geometries:
Slider through different attributes (to be set in the view's conf. window). Geometry doesn't change. Values to be shown yes.

In general, by default none of them is activated. When a time attribute in posix is recognized, the time slider is activated (like now). When a user activates one of the other options (only one) in the view's configuration window, the chosen slider will be available. Only one slider will be available per view. Therefore, if a "mxt0" attribute is present in the attribute table but the user activated one of the discrete sliders the time slider won't be available anymore.

**# Further information:**

**Time slider:**
Already implemented. 
Works for continuous time-related data only. 
Suitable for:
- Datasets with features that can be shown together on map even if they do not share exactly the same time value.
- Features which absolute-time distance is to be respected when moving the cursor along the slider.

**Discrete slider for different geometries:**
To be implemented. 
Slider through absolute values of one specific attribute (to be set).

Needed for datasets consisting of features that are grouped in sets of features with an equal attribute value (it could be an "year" but also a random numeric value (0,1,2,3,4....).
Suitable for:
- Datasets with sets of features (or even only 1) that must be shown alone (e.g. urban extent evolution through time).
- Datasets that should always show something on map (absolute distance between sets of features is not important; we must always move througn the list of absolute values of the attribute that is set for the slider).

The discrete slider should work in a similar way than the "Filter by numeric value" that is already available for vector tile views. However, the discrete slider should be featured with only one cursor (the value is defined, not an interval).

The slider should be hidden by default unless the owner of a view set it up and select the source variable to be employed. If the source variable is numerical the order of appearence of features when moving across the slider should be from lower values to higher values. For cathegorical variables it may or may not be possible to use the discrete slider because I don't see much of chances to use it with such variables (if yes, what about alphabetical order?) 

**Discrete slider for same geometries:**
To be implemented.
Needed for datasets consisting of superposed features with exactly the same geometry but with different values to be shown.
Suitable for:
- National, regional, provincial data in general where data is always associated to a stable geometry (administrative domain).

Instead of uploading one dataset per each year this slider will allow publishing everything into the same dataset. Each year's values would be stored in a specific attribute. In the configuration window of the view the user should activate this slider and set the list of source variables to be employed in this slider.

**Comment by thomaspiller** [comment]
Currently, it is possible to do what is asked in this issue through the use of a dashboard (which requires coding capabilities). @antobenve Is it enough to cover our needs? Can we close this issue for now?
