### ISSUE TITLE
Story maps edition: improvements

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/mapx#260]
Here is a list of possible improvements to facilitate the story map edition:
- [ ] **Font**: Currently, there is only one font available.
_Suggestion_: If possible, there should be an option to choose the font type in the little edition box ( blue pen button --> edition box)
- [ ] **Slide size and position**: Currently, the position of the slides is defined according to the classes pre-defined in MapX. It would be easier to be able to modify these slides in the edition box:
  * define the slide position using the classes (already existing)
  * edit the slide box in the edition mode (blue pen --> edition mode)
  * then in the edition mode, it should be possible to:
    1. modify the size of the box manually (like for the images: a double arrow in the corner of an image allows to modify its size)
    2. position manually the slide box if necessary (like in word or powerpoint)
- [x] **Legend**: We need a **real** system of legends in story maps; maybe a legend that is collapsed on a corner by default and that can be expanded if necessary to check the content. So far, we add the legends as images, and it doesn't look very professional...
_Edit_: this point is particularly important, especially now with WESR: story maps are published and reflect the content of the platform for a large audience. @thomaspiller @PierreLacroix is it something that could be on the agenda? 
- [x] **Font size**: Currently the font size is applicable to the entire slide content, it is not possible to select a different font size for a part of the content only. 
_Suggestion_: The font size should appear in the little edition box (blue pen button --> edition box) aside from the other options like "bold", "italic" etc etc. It should be possible to use different font size if necessary in one single slide.
- [x] **Data provider**: Similar comment than for the post above: for each layer displayed in the story map, the data provider should appear clearly. Maybe as part of the legend?

**Comment by fxi** [comment]
Is "Font size"  meant to be checked ? Is it ok ?

For the legends here is a preview:

![mx_story_legends](https://user-images.githubusercontent.com/1196833/66921006-adfc6900-f024-11e9-959d-2e7b30c4bfdb.gif)

**Comment by MarionPlanque** [comment]
It looks fantastic!! 
Do you have an overview of the legend is there are MANY views activated or a very long legend? In a nutshell, if the legend window is longer than the height of the screen

**Comment by MarionPlanque** [comment]
For the font size, it's still a "problem".
It's not a bug in the story map, it doesn't prevent users to create story maps, but it's quite tricky: if one wants to have different fonts in a slide, multiple slides must be created and superimposed with different levels of transparency.

**Comment by fxi** [comment]
Long legends : If many legends are displayed at once or if a view's legend is very long, the legend panel will have a scroll bar. I've also tried multi-column mode but it's hard to determine which legends should have a multi-column layout and which don't. This could perhaps be set at the view's level, in the view editor in a next version.

For the font size, we can uncheck the item and I will do something later.

**Comment by thomaspiller** [comment]
I am closing this issue as it is planned to refactor the story maps tool in the medium term. Comments from this issue were taken into account during the MapX team's technical discussions on the subject.
