### ISSUE TITLE
Change [story] with [real name of the project] in "Views to activate" in story map.

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#525]
Views that are in use in a story map are listed with the prefix [story] in the story map module under "Views to activate". 

I suggest to always clearly display the name of the project in which a view is, rather than using "[story]", even for those views that are already in use in a story map.

This will help editors understanding what the view in a step is about.

**Comment by thomaspiller** [comment]
I agree however, I think it would still be necessary to indicate in one way or another that the view is already used in another step of the story map.

**Comment by antobenve** [comment]
Surely a compromise is a good idea.

**Comment by fxi** [comment]
It's possible to add much more information, such as project, description, source, extent, keywords... The dropdown/search component can be quite complex. For example, the list of sources contain also list of view, size, date... :
<img width="507" alt="image" src="https://github.com/unep-grid/mapx/assets/1196833/2c76420d-0354-4d70-8f5c-ddea26ffe593">

**Comment by fxi** [comment]
All project's views should be listed, based on user rights + views already there + pasted views id + all public views
For the views position, this should work : 
![mx_story_map_drag_drop](https://github.com/unep-grid/mapx/assets/1196833/532b7d18-a790-43e2-ac05-9c67a8b6674c)

**Comment by thomaspiller** [comment]
I had the wrong logic in mind for non-public views. I thought that all private views would be listed but in fact, only the private views of the current project are listed. I will retest everything as soon as possible and let you know if everything works well.
