### ISSUE TITLE
Sharing of views between projects: improvements

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#527]
As suggested in issue #517:
- [ ] Add a checkbox in "configure this view" where publishers and admins can decide "this view can be shared to other projects"

**Comment by antobenve** [comment]
If this request will be implemented, I suggest that the new option will be toggled on by default. 
Views should be sharable unless this is specifically forbid by publishers.

**Comment by thomaspiller** [comment]
@PierreLacroix @antobenve Is the development of this feature still required/wanted?

**Comment by PierreLacroix** [comment]
No, I don't think it is still wanted

**Comment by thomaspiller** [comment]
Alright, I'm closing this issue and we'll reopen it if necessary.
