### ISSUE TITLE
Zoom parameters affect feature size on map, but not in legend

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#779]

**Comment by fxi** [comment]
Not clear. This was part of a previous issue #777, with a completion message, no further information on that issue. I can investigate, but it would be better to actually explain the part of the issue that  is not solved by the original fix.

**Comment by antobenve** [comment]
Hi @fxi , I wrote the issue #777 but I can't remember right now more information about this specific point. Maybe we can close the issue and re-open it in case we feel this need in the future?

**Comment by fxi** [comment]
@antobenve Hello, yep, we can close that. If required, reopen a new one with a bit more context, a screenshot, and/or a small description of how to reproduce, what should happen, if not obvious. If there is something I missed in a previous, similar issue, just mention that too.

**Comment by antobenve** [comment]
OK. The issue is closed.
