### ISSUE TITLE
Ease the process of sharing a temporary view to a project - after the use of the "Catalog" search tool

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#780]
The search tool allows to easily discover views that publishers might want to add to their project. Currently, a smooth solution to share these views to a/the_current project does not exist.

Here some propositions:

1. Temporary views that are displayed in the project's catalogue have the "Share to a project" button. The sharing tool is exactly the one that exists for normal views. The list of projects allowed in the tool depends on the user ID solely.
2. The same views have a button "share to this project" that is only visible to the publishers of the current project. The tool does not allow the selection of any project. It simply performs the action when it is clicked using the ID of the current project. It depends on the current project ID and the user role. The view is added to "views_external" like for option 1.

Security issues might preclude one or both options. These must be evaluated more in detail in the next days.

**Comment by thomaspiller** [comment]
A solution has already been implemented in MapX.
