### ISSUE TITLE
Search tool API: geographic keywords translation 

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#787]
The _source_keywords_m49_ key contains the codes of the geographic entities. It would be relevant to add an additional key containing their translation in the language of the index. As is the case for the keywords GEMET.

**Comment by fxi** [comment]
Two approaches :

1) new key `source_keywords_m49_data` with key-value pairs `{id:m49_15, label:'North Africa'}`.  sql + routines + tests + debug, ~ 1 day
2) rewrite old key, same as above but re-using same key `source_keywords_m49` + rewrite m49 keys system in the app search tools + remove live translation ( as the translation would be included in the returned object ) ~ 2 days
