### ISSUE TITLE
Map projection improvements

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#807]
Although this feature is at an early stage of development. Here is a list of improvements to keep in mind.

- [ ] when accessing a project from a link, the map loads with the Web Mercator projection then after 1-2 seconds the map is updated to use the projection defined in the project settings.
- [ ] globe + 3d terrain: the camera angle causes the globe to move and partially slide it off the screen

**Comment by antobenve** [comment]
Just adding to this issue that:
- [ ] when using the LambertConformalConic projection, the "zoom to" button of views (rasters and vectors apparently) doesn't produce the expected behaviour: the map zoom doesn't match the data extent. 

To test if this problem occurs with other projections too.

**Comment by antobenve** [comment]
Projections need to be done on the fly: the point where the mouse is clicking must be used to get the lat/long on which the projection is calculated. Otherwise it feels static. Same for when the mouse zoom to an area.
[Earthnull ](https://earth.nullschool.net/)is a good example.

**Comment by thomaspiller** [comment]
I am closing this issue as the map projections have been removed from MapX for the time being as the way they have been implemented did not satisfy us.
