### ISSUE TITLE
Custom code view: pop-up edge case

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#819]
In the following situation:
- view type: cc
- source type: raster

a click in the map does not display the pixel value in the pop-up (`[ No value ]`).
If the source is of vector type, the pop-up works as expected.

**Comment by fxi** [comment]
Ok. 
If the raster layer is not from a WMS service or if "queryable" is not enabled ex.[ in geoserver](https://docs.geoserver.org/main/en/user/data/webadmin/layers.html#data-webadmin-layers:~:text=WMS%20Settings-,Queryable,-%E2%80%94Controls%20whether%20the) the module will not work.

In the case of  [this example](https://app.staging.mapx.org/?language=en&project=MX-QNN-G0C-I6F-GZB-MPA&viewsListFlatMode=false&viewsOpen=MX-XISB3-02Q7O-STCVM&viewsListFilterActivated=true&p=0&b=0&z=6.79&lat=-0.74&lng=31.015&t3d=false&sat=false&theme=color_dark&globe=true), it works : 

<img width="1027" alt="image" src="https://github.com/unep-grid/mapx/assets/1196833/5b85d56a-4d20-4d0b-b46a-adbed1b4952f">

**Comment by thomaspiller** [comment]
Indeed, the module works fine. I close this issue as the reported glitch is data specific and not related to MapX.
