### ISSUE TITLE
Map composer: calculate max dpi according to export dimensions

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#857]
If the PNG file generated by the **Map Composer** exceeds a pixel limit (I think it's 16 million), it has offset elements.
To avoid this, it will be interesting to add to the **Map Composer** a system to calculate the max resolution (dpi) according to the dimensions selected by the user.

**Comment by fxi** [comment]
Reported by @thomaspiller after latest fix : 

- Multiple warnings clutter the interface when the composer reaches its maximum size.
- It's still possible to export an oversized canvas by manually adjusting the dimensions.

**Comment by thomaspiller** [comment]
Feedback on my tests:
- when the map composer is loaded, the "dpi" input is displayed while the default unit is "px"
- When changing units, width and height are recalculated correctly. However, the "dpi" can be modified and we can go beyond the export limit area.
