### ISSUE TITLE
Sharing sources between projects (open discussion)

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#874]
In MapX, data sources are compartmentalized by project. This means that it is only possible to create views in the project where the source was published. This logic has been set up to ensure maximum security within projects but in some cases, it would be interesting to have sources accessible to all projects. This would avoid data duplication and also ensure that the data version and metadata are identical across all projects. I am thinking in particular of certain public base data such as the EEZ.

One approach I've come up with might be to have one project dedicated to public base data (managed by UNEP/GRID-Geneva) and make them available in all other MapX projects.

Another approach could be to add a share option (read only) in the manage source tool. Publishers/administrators would then have the choice to make a source public outside of their project or not.

These approaches have not been evaluated and remain speculative, but I think this is something we should discuss in more detail early next year.

**Comment by fxi** [comment]
We can imagine a new tool for superusers, to manage all sources from `mx_sources`, using a  web based spreadsheet editor : 

- Quickly check how many views are linked, and how many joins are used
- Filter by project / size / etc.
- Batch removal / export
- Aliases creation
- List size / resources used
- Enable disable global mode ⤵

Global mode = a boolean attribute / checkbox "Enable global" would enable / disable a source to be available in every project. Global sources cannot be deleted. Metadata should be edited from the table or from the project, as any other sources.

**Comment by thomaspiller** [comment]
Moved to #953
