### ISSUE TITLE
Reporting system for problematic content (open discussion)

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#876]
It would be interesting to develop a system in the MapX interface so that users can report problematic content (eg outdated, non-functional, erroneous) to the MapX team.

This could be for example a clickable flag that opens a panel allowing users to describe the issue in a few lines.

**Comment by thomaspiller** [comment]
We could link this tool to a Github repo which could be used as a ticket system combined with a Github project to indicate the processing status. Each problem reported would then be converted into an issue. The user would define the type of issue (converted to labels in the repo, e.g. outdated, no longer working, offensive content), a title and a detailed description.

**Comment by fxi** [comment]
In the UI, this could be a in a modal :

Report a issue :
- bug, feature request -> mapx code repo
- data/widget -> mapx data public repo
- confidentiality/legal issue -> email form to the publisher + admin

**Comment by PierreLacroix** [comment]
This tool should be kept simple. 
First step: a user selects the type of reporting, e.g., 1. institutional, administrative, general information needed ; 2 data issue ; 3. bug, feature improvement or request. 
Second step: depending on the choice made, the user is redirected towards: 1. an email to a generic email address (to discuss: MapX manager or MapX core team or workspace admins) ; 2. a simple formular connected to the data reporting system ; 3. the MapX code reporting system. 
To discuss: how to deal with requests that are not using a proper terminology, or that are not precise enough.
