### ISSUE TITLE
MapX init: create folders if not available

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#897]
To ease MapX deployment, if the folders defined by the `MAPX_PATH_USERDATA` and `MAPX_PATH_DOWNLOAD` environment variables are not present, the `API` should create them.

**Comment by fxi** [comment]
Solved in https://github.com/unep-grid/mapx/commit/827aecb88c8d3db9be0611d7d1ad3b1bb0e85125

**Comment by thomaspiller** [comment]
Tested on a local stack and it works as expected
