### ISSUE TITLE
Improve the distinction between public and private views

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#898]
Having discussed with some MapX users/publishers, it appears that the distinction between public and private views might not be clear enough (green ✓ to identify public views).

Therefore, I open the discussion and propose to think about a way to improve this.

I see 2 options that could be combined:

1. non-public views -> slightly mutated title (medium grey)
2. a specific badge for each class of read rights, e.g.:
    - public: green ✓ (current solution)
    - member: yellow `M` icon
    - publishers: red `P` icon
    - admin: red `A` icon

What do you think about it?

**Comment by antobenve** [comment]
Both solutions are fine for me but I prefer the number 2 as it also encourage publishers to open rights to other publishers or members for private views rather than keeping them for themselves.

**Comment by PierreLacroix** [comment]
In terms of graphic semiology, we must avoid varying two visual variables (color and shape) at the same time to show progression. Consider varying only the color. 
I'm also not either sure about the progression “green => orange => red”: users (admins in this case) will think that there is an issue on certain views. 
Finally, the tooltip “This view is publicly available” should be extended to the other reading rights.

**Comment by antobenve** [comment]
I also think we are fine as we are now.

**Comment by fxi** [comment]
I think it's best to use the filters. If a visual feedback is required, we should probably also refactor the layout for badges container, as it can look quite busy.  With the current roles inheritance, we could also ignore intermediate reading groups.  
<img width="454" alt="image" src="https://github.com/user-attachments/assets/f3548d98-fb03-4df1-8392-85a188c9b552">

**Comment by PierreLacroix** [comment]
It's fine as it is now. In my previous comment I had expressed doubts as to the feasibility in semiological terms
