### ISSUE TITLE
AutoStyle - head/tile breaks actually uses "equal_interval"

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#900]
The classes generated when selecting the "head/tile breaks" or the "equal intervals" binning method in the AutoStyle module are the same. It seems the method used is "equal_interval" in both cases.

**Comment by antobenve** [comment]
It seems it uses two different methods, however the results don't change (maybe a coincidence?) and this is reported in both cases `Table ( Method : equal_interval, number of bins : 5, count 19 )`

**Comment by fxi** [comment]
The request is wrong : `head_tails` vs `heads_tails`

**Comment by fxi** [comment]
Which is automatically converted to `equal_interval` here : 
https://github.com/unep-grid/mapx/blob/main/api/modules/route_validation/rules.js#L177

**Comment by antobenve** [comment]
Seems fixed in [v.1.11.0-alpha.3](https://github.com/unep-grid/mapx/commit/a9b14a639518791c74f0c073e1c4f62fed2c5842)
