### ISSUE TITLE
Cache issues when a row is deleted from a source

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#901]
The method in place to handle the cache - based on the pg_xact_commit_timestamp(xmin) related to the edits of a table in PostgreSQL - is not reliable in case one row is deleted (currently only possible from the db) because the timestamp associated to the deleted row is also deleted. 

In fact the timestamps are stored in Postgres row-wise. When a row is deleted, its timestamp is also deleted. The function [getSourceLastTimestamp(idSource)](https://github.com/unep-grid/mapx/blob/de7bd86d711f41e65068f7a501acaeaec09a4331/api/modules/db-utils/index.js#L472) in place to retrieve the most recent change in a source will get therefore an older timestamp and the cache associated to this will be used by the app.

A method is needed to update the LastTimestamp of a source when a row is deleted to avoid its cache to be used further.

This problematic could be handled either by
1) storing the LastTimestamp of each source in mx_sources and use it to compare the LastTimestamp retrieved by the function and invalidate the cache in case the value in mx_sources is more recent than the value retrieved by the function (time demanding method)  or
2) developing a method for deleting rows from the table editor in MapX. This new method should allow the selection and deletion of a row and generate a new timestamp to be used by the application to handle the cache.

**Comment by fxi** [comment]
Converted `commit timestamp` to update `date_modified` in `mx_sources`
When a row is deleted manually, stats, tiles can be invalidated by updating the `date_modified` 
-> for developing a "remove row" from the editor, this is much more involved and should be discussed. 
-> the current "fix" is available in `1.11.0-alpha.8`
