### ISSUE TITLE
Adding a view via SDK duplicates views in the panel list

### ISSUE THREAD

**Issue by trepmag** [unep-grid/mapx#904]
Observed on staging (19-apr-2023); example: https://codepen.io/trepmag/pen/eYPdrOo?editors=0010

![image](https://user-images.githubusercontent.com/875021/233116984-9a9fbc8f-bd8d-4950-a756-0c2fdc8d6fd0.png)

**Comment by fxi** [comment]
This should be available in prod, version 1.11.0
