### ISSUE TITLE
Search tool: reorder the list of countries in the advanced filters

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#918]
In the **Advanced filtering options** of the search tool, the countries listed in the **Geographical keywords** section should be sorted alphabetically and not by occurrence count.

For the other sections, would it be relevant to do the same? What is your opinion on this?

**Comment by PierreLacroix** [comment]
The same concept can be applied to the regions, with "World" staying in first position. For what concerns the keywords, keeping them sorted by occurrence count is fine for me.
