### ISSUE TITLE
WMS publication issues on MapX

### ISSUE THREAD

**Issue by sbellieres** [unep-grid/mapx#926]
Dear Sir, Dear Madam, 
I'm a MapX publisher working for Plan Bleu, at Marseille. Since April 2023 I've published lots of views in MapX (vectors and rasters). Nevertheless, since the last MapX update I've met some issues in order to publish WMS view. 
Indeed, I follow exactly the WMS publication steps in the MapX WMS configurator panel, but in the end I only have a legend without cartographic visualization as follow : 

![WESR_ Mediterranean et 11 pages de plus - Personne](https://github.com/unep-grid/mapx/assets/141031603/03f14c40-87b4-4480-b6fe-e8d94226d482)

I've encountered the same issue for a marine.copernicus WMS flux which I've tried to integrated into MapX...
May you have a solution to resolve such problem ? 

Thank you in advance, dear Sir, dear Madam, for your response and your help.
Cordially,
Samson Bellières

**Comment by sbellieres** [comment]
Here the view's link :
*https://app.mapx.org/static.html?language=en&views=MX-XHKHL-V03BN-G61DU&zoomToViews=true&p=0&b=0&z=5.314&lat=38.431&lng=13.319&t3d=false&sat=false&theme=classic_light&globe=false
<https://app.mapx.org/static.html?language=en&views=MX-XHKHL-V03BN-G61DU&zoomToViews=true&p=0&b=0&z=5.314&lat=38.431&lng=13.319&t3d=false&sat=false&theme=classic_light&globe=false>*

Samson Bellières

Assistant de projet en croissance et économie bleue

Tour la Marseillaise – 16ème étage

2 bis, Boulevard Euroméditerranée - Quai d'Arenc

13002 Marseille

Tel : +33 (0)6 40 34 49 52

www.planbleu.org

[image: logo_signature-email]

**Comment by fxi** [comment]
As requested by the mapx administrator, this issue will initially be handled as data support, and if a bug is found, it will be added here. 

What I can see:

- The WMS endpoint uses `https://` : mirroring is not required. Mirroring is also useful only if their CORS policy is restricted, and even then, it's probably better to obtain their consent and add mapx.org as accepted origin.
- All requests are returning valid -  but empty – tiles; no data is available at the current extent, or there may be another issue, such as one related to projection.

**Comment by antobenve** [comment]
@sbellieres answered positively to me by email a few weeks ago. I forgot to close the issue. I'm doing it now.
