### ISSUE TITLE
Hotspots prototype:

### ISSUE THREAD

**Issue by fxi** [unep-grid/mapx#929]
From @PierreLacroix note:
- 4 side-by-side images (or a 2x2 grid of images)
- Zooming and panning in one of the images will zoom accordingly in the 3 other images

**Comment by fxi** [comment]
@PierreLacroix FYI, will be discussed with @thomaspiller next week

- 2x2 grid, split, sync, unified, ticks
https://unep-grid.github.io/mapx-demo/examples/maps_sync/four_maps.html

- 1x2 grid, split, sync, ticks, unified
https://unep-grid.github.io/mapx-demo/examples/maps_sync/two_maps.html

- Four in a row, no split, sync, no ticks, not unified
https://unep-grid.github.io/mapx-demo/examples/maps_sync/four_maps_row.html

- 2x2 grid, no split, sync, not unified, ticks
https://unep-grid.github.io/mapx-demo/examples/maps_sync/four_maps_no_split.html

**Comment by thomaspiller** [comment]
Many thanks.
The prototypes respond well to the need for the hotspots website.
I am closing the issue as the code has been published online.
