### ISSUE TITLE
Duplicate views in the Catalog

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#932]
When doing a search in the catalog, some views are duplicated.
To reproduce this, just do a search for the text "twap". 9 hits are returned but in the list of views, about twenty are displayed when scrolling in the panel (duplicates).

**Comment by fxi** [comment]
Could be linked to the update(append=true) + offset issue. 
We already had some pagination issues in [711](https://github.com/unep-grid/mapx/issues/711) linked to how this early version of meilisearch works : [561](https://github.com/meilisearch/documentation/issues/561)
