### ISSUE TITLE
Add OpenStreetMap attribution

### ISSUE THREAD

**Issue by flacombe** [unep-grid/mapx#936]
Dear maintainers,

Some (most?) of projects hosted on your https://wesr.unepgrid.ch/ website are using background maps that make usage of OpenStreetMap data.
It is perfectly fine and it's nice to see such an usage on some of UN services.

However, it should be properly attributed as defined on https://osm.org/copyright, in any case.
Some base layers come from Mapbox, Thunderforst, whatever. It should be attributed the same way.

Can you do necessary modifications to bring this online if you please?

Best regards

**Comment by flacombe** [comment]
Hi @fxi 

Thanks for the quick answer!

> Re-adding the classic OSM attribution, as shown in the screenshot of the bottom right of the map, should however address this issue.

Yes, that will be okay then.

Let's keep it open until the corresponding release.

**Comment by thomaspiller** [comment]
Hi @flacombe,

We have just deployed a new version of MapX online which credits OpenStreetMap properly.

**Comment by flacombe** [comment]
It's great, thank you for your support :)
