### ISSUE TITLE
Popup improvements 

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#941]
- [x] Allow users to resize the pop-up
- [x] Allow users to close the pop-up but keep the filter(s) on #446

**Comment by thomaspiller** [comment]
To close the pop-up while keeping the filters activated, a solution could be to have a 2nd button next to the `x`.

**Comment by antobenve** [comment]
Something like `✓` button.

**Comment by fxi** [comment]
I propose moving the popup content to an “Attribute Widget.” This change ensures that the content is not intrusive but can be shown or hidden via the dashboard panel. The filtering mechanism will be retained, with two buttons: Close and Reset.

The widget will not be triggered if another widget already has control and is using the data from the selected feature. When the user clicks on a different feature, the same widget will update, functioning as the current popup does.

Currently discussed, we will refine this using admin/publisher's feedback. Not definitive. 


![Image](https://github.com/unep-grid/mapx/assets/1196833/75993f5b-2775-44d8-8934-ee6883f61955)
