### ISSUE TITLE
Suggest terms for free keywords

### ISSUE THREAD

**Issue by daohy** [unep-grid/mapx#942]
Suggest terms for free keywords, e.g. based on free keywords already entered by others, or on GEMET terms. It would be only suggestions, any term could still be entered. But this might help reduce the heterogeneity of the words (and spelling) of these keywords (913 terms as of 14.09.2023, with some redundancies due to mispelling such as "bathimetry" and bathymetry)

**Comment by thomaspiller** [comment]
Excellent idea, I add this issue to the STT. I also suggest correcting keywords in the database when it's obvious they are typos.

**Comment by thomaspiller** [comment]
In addition, keywords could be stored in the database in lower or title cases. This would avoid having duplicates depending on the casing used by publishers.

**Comment by thomaspiller** [comment]
It might be wise to only list keywords related to public content in MapX.
Indeed, they are not always filled correctly, particularly in views/sources in “self” mode or for tests.

**Comment by fxi** [comment]
Instant Search Keywords To-Do List:

- [x] Materialized view with keywords + GIN index (Generalized Inverted Index) using trigrams (pg_trgm module) + trigger + migration script + routine tests
- [x] Websocket methods: server (with parametrized query + publisher auth) + client wrapper
- [x] Metadata editor: custom resolver for keyword search
- [ ] Cleaning script: handle typos and duplicates @PierreLacroix, @thomaspiller : should probably tracked in another issue.

https://github.com/unep-grid/mapx/assets/1196833/3d5a4bad-7e2d-4cde-891e-bdf30729d161

**Comment by thomaspiller** [comment]
As suggested by @Fred, I opened a new issue to track the keyword cleanup issue.
