### ISSUE TITLE
Development of a new tool to create a source derived from a join between two MapX sources

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#944]
The tool for creating these new “join” type sources must allow defining:
- the source name
- the two MapX sources to join (vector or tabular)
- the columns to use for the join
- the attributes to include in the source from the 2 pre-existing MapX sources
- the type of join: inner or left join

The management of this new type of sources will be done from the “Manage sources” tool:
- update of join parameters
- rights management
- sharing management (:warning: if UN borders are used, the download must not be activable)

The attribute table editing and metadata creation tool must be disabled for all “join” type sources.

When a “join” type source is used in a view, the metadata from both sources will simply be displayed in the metadata panel.

**Comment by PierreLacroix** [comment]
I suggest that the tool is available for developers only in a first step, and for publishers after a period of usage in real conditions.
It would also be good if users could identify easily a source that has already undergone a join, e.g. through a new color.
