### ISSUE TITLE
Integrate information about UNMap disclaimers in the Map Composer

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#962]
The UNMap guidance document indicates that a disclaimer should always be indicated when exporting maps that shows the administrative boundaries.
Additional disclaimers are also mandatory when exporting specific countries at high zoom levels.

To comply with these rules MapX could:
- offer a text box with the general disclaimer in the map composer;
- Add a footnote above the "Close" and "Help" buttons that indicates:
"Special disclaimers must be placed in combination to the general disclaimer when showing the administrative boundaries of special regions. See disclaimers and rules here [LINK to wiki with instructions and examples] "
- The text box with the general disclaimer should be editable (in case the additional disclaimer must be added to it) and removable (in case the administrative boundaries are not visible in the map - we still want to give freedom to the users)

**Comment by thomaspiller** [comment]
Linked to #951

**Comment by fxi** [comment]
After discussion with @antobenve, it became clear that we needed to provide all the required attributions, disclaimers, licenses, and metadata from all layers, views, and sources present in the MapComposer output – not in the UI. 

I addressed this by providing ZIP archives with all the related files, which should be validated before this change occurs in the next version. 
 
<img width="396" alt="image" src="https://github.com/unep-grid/mapx/assets/1196833/87aa1ed0-1c62-41e1-bbb8-e712f1471cac">

**Comment by fxi** [comment]
-> available in 1.13.5-alpha.1, staging
