### ISSUE TITLE
Add views based on “join” type sources to the Meilisearch indexes

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/mapx#974]
Views based on “join” type sources (see #944) must be added to the [Meilisearch indexes SQL query](https://github.com/unep-grid/mapx/blob/staging/api/modules/template/sql/getViewsPublicForSearchIndex.sql).
Like this, all public views will be listed in the MapX views catalog.

**Comment by fxi** [comment]
I think it's working fine : views using sources of type 'join'  should not be different than other views. Maybe a mix up with WMS services not implemented for source of type `join`, preventing them to be listed in GeoServer ?

**Comment by thomaspiller** [comment]
Indeed, I have just done a test on MapX staging and `vt` views using `join` sources are included/returned in the query. I'm closing the issue for now.
